# Generated by Django 6.0.7 on 2026-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User'), ('photographer', 'Photographer')], db_index=True, default='user', max_length=20),
        ),
    ]
