# Generated by Django 6.0.1 on 2026-09-07 04:41

import App.Storage.storage_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_subscriptionplans_photographerprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('reception', 'Reception'), ('engagement', 'Engagement'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('corporate', 'Corporate Event'), ('family', 'Family Function'), ('other', 'Other')], default='wedding', max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('access_code', models.CharField(db_index=True, default=App.Storage.storage_models.generate_event_access_code, max_length=50, unique=True)),
                ('pin_code', models.CharField(blank=True, help_text='Optional PIN code required for guests to view/download photos', max_length=20, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='When True, accessible via access code. When False, gallery is hidden')),
                ('allow_downloads', models.BooleanField(default=True, help_text='Allow guests to download individual photos or the bulk ZIP')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_events', to='App.photographerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('category_tag', models.CharField(blank=True, default='', help_text='Tag like Ceremony, Reception, Stage, Candid, Dinner', max_length=100)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='App.sharedevent')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
