# Generated by Django 6.0.1 on 2026-09-08 15:13

import App.Storage.storage_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_sharedevent_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='storage_reserved_bytes',
            field=models.BigIntegerField(default=0, help_text='Storage temporarily reserved during in-flight uploads in bytes'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text='Current total storage used across all galleries in bytes'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='face_search_enabled',
            field=models.BooleanField(default=True, help_text='Whether face search feature is enabled for this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='max_galleries',
            field=models.PositiveIntegerField(default=50, help_text='Maximum active galleries allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=53687091200, help_text='Storage limit in bytes'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private (Invite Only)'), ('password_protected', 'Password Protected')], default='public', max_length=30)),
                ('share_token', models.CharField(db_index=True, default=App.Storage.storage_models.generate_secure_share_token, max_length=64, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloads_enabled', models.BooleanField(default=True)),
                ('face_search_enabled', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='App.photographerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkDownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('archive_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_download_jobs', to='App.gallery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(db_index=True, max_length=512)),
                ('original_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('preview_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('file_extension', models.CharField(default='.jpg', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Exact file size in bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds if video', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('upload_status', models.CharField(choices=[('reserved', 'Reserved'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='App.gallery')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='App.photographerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='App.media'),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(help_text='Internal vector array representation')),
                ('bounding_box', models.JSONField(blank=True, help_text="{'x': int, 'y': int, 'w': int, 'h': int}", null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='App.gallery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='App.media')),
            ],
        ),
        migrations.CreateModel(
            name='StorageAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.gallery')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_audit_logs', to='App.photographerprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_bytes', models.BigIntegerField(help_text='Estimated upload size')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Auto-expires if upload not finalized')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_reservations', to='App.gallery')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_reservations', to='App.photographerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryClientAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('can_download', models.BooleanField(default=True)),
                ('can_face_search', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='App.gallery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gallery', 'user', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'created_at'], name='App_media_gallery_51ce03_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['photographer', 'file_size'], name='App_media_photogr_e6279c_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['processing_status'], name='App_media_process_a714bc_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['deleted_at'], name='App_media_deleted_dbfd97_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['photographer', 'created_at'], name='App_gallery_photogr_1da5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['share_token'], name='App_gallery_share_t_78c288_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['status', 'visibility'], name='App_gallery_status_8d97d5_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['gallery'], name='App_faceemb_gallery_f94a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['media'], name='App_faceemb_media_i_59c699_idx'),
        ),
        migrations.AddIndex(
            model_name='storageauditlog',
            index=models.Index(fields=['photographer', 'action'], name='App_storage_photogr_13447d_idx'),
        ),
        migrations.AddIndex(
            model_name='storageauditlog',
            index=models.Index(fields=['timestamp'], name='App_storage_timesta_5b0c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadreservation',
            index=models.Index(fields=['photographer', 'status'], name='App_uploadr_photogr_1ddfec_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadreservation',
            index=models.Index(fields=['expires_at'], name='App_uploadr_expires_3a7823_idx'),
        ),
    ]
