# Generated by Django 6.0.7 on 2026-09-12 07:15

import App.Subscriptions.sub_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_photographerprofile_storage_reserved_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryClientSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('client_notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_client_visited', models.BooleanField(default=True)),
                ('notify_photos_downloaded', models.BooleanField(default=True)),
                ('notify_favorites_selected', models.BooleanField(default=True)),
                ('notify_storage_alerts', models.BooleanField(default=True)),
                ('notify_marketing_updates', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_gateway_ref', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bulkdownloadjob',
            name='download_type',
            field=models.CharField(choices=[('master_all', 'Master All'), ('selected_subset', 'Selected Subset')], default='master_all', max_length=30),
        ),
        migrations.AddField(
            model_name='bulkdownloadjob',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='allow_downloads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='allow_favorites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='template_id',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('masonry', 'Masonry'), ('cinematic', 'Cinematic'), ('minimal', 'Minimal')], default='editorial', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='video_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='video_stream_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('client_visit', 'Client Visit'), ('download', 'Download'), ('proofing_submitted', 'Proofing Submitted'), ('storage_warning', 'Storage Warning'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='App.photographerprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_gallery_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photographer_profiles/'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='default_template',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('masonry', 'Masonry'), ('cinematic', 'Cinematic'), ('minimal', 'Minimal')], default='editorial', max_length=50),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='enable_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='location',
            field=models.CharField(blank=True, default='Milan & San Francisco', max_length=255),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='studio_name',
            field=models.CharField(default='LUMIÈRE STUDIO & ATELIER', max_length=255),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='watermarks/'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_opacity',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_position',
            field=models.CharField(choices=[('center', 'Center'), ('bottom_right', 'Bottom Right'), ('bottom_left', 'Bottom Left'), ('repeated', 'Repeated')], default='bottom_right', max_length=50),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_text',
            field=models.CharField(default='© Ex Studio', max_length=255),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='allowed_templates',
            field=models.JSONField(default=App.Subscriptions.sub_models.default_allowed_templates, help_text='List of gallery layouts enabled for this tier'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='annual', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='features_list',
            field=models.JSONField(default=App.Subscriptions.sub_models.default_features, help_text='Display bullet points for pricing UI'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=39.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('studio', 'Studio'), ('master', 'Master')], default='pro', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='video_delivery_enabled',
            field=models.BooleanField(default=True, help_text='Whether 4K video asset streaming is enabled'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='watermark_customization',
            field=models.BooleanField(default=True, help_text='Whether studio watermarking suite is enabled'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding',
            field=models.JSONField(help_text='Internal 128-dimensional normalized vector array'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '02:45'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='App.subscriptionplans'),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='face_search_enabled',
            field=models.BooleanField(default=True, help_text='Whether AI face search feature is enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='max_galleries',
            field=models.PositiveIntegerField(default=0, help_text='Maximum active galleries allowed (0 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=128849018880, help_text='Storage limit in bytes'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['slug'], name='App_gallery_slug_139df6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'display_order'], name='App_media_gallery_aafdae_idx'),
        ),
        migrations.AddField(
            model_name='galleryclientselection',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_selections', to='App.gallery'),
        ),
        migrations.AddField(
            model_name='galleryclientselection',
            name='selected_media',
            field=models.ManyToManyField(blank=True, related_name='client_selections', to='App.media'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='App.photographerprofile'),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='App.photographerprofile'),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_subscriptions', to='App.subscriptionplans'),
        ),
    ]
