# Generated by Django 6.0.7 on 2026-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_galleryclientselection_notificationpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordlessLoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Passwordless Login OTP',
                'verbose_name_plural': 'Passwordless Login OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
