# Generated by Django 6.0.7 on 2026-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_passwordlessloginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='studio_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
