# Generated by Django 6.0.7 on 2026-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_photographerprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
