# Generated by Django 6.0.7 on 2026-09-17 10:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def seed_plans_before_alter(apps, schema_editor):
    Plan = apps.get_model('App', 'Plan')

    seeds = [
        # Legacy IDs so existing rows don't violate FK constraints
        {
            "id": "1",
            "name": "Starter Plan",
            "subtitle": "Starter",
            "tier": "standard",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 200.00,
            "total_price": 2400.00,
            "currency": "INR",
            "image_storage_gb": 50,
            "video_storage_gb": 0,
            "storage_limit_bytes": 53687091200,
            "is_active": False,
        },
        {
            "id": "2",
            "name": "Pro Studio",
            "subtitle": "Pro",
            "tier": "standard",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 800.00,
            "total_price": 9600.00,
            "currency": "INR",
            "image_storage_gb": 120,
            "video_storage_gb": 0,
            "storage_limit_bytes": 128849018880,
            "is_active": False,
        },
        {
            "id": "3",
            "name": "Studio Luxe",
            "subtitle": "Luxe",
            "tier": "premium",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 1800.00,
            "total_price": 21600.00,
            "currency": "INR",
            "image_storage_gb": 500,
            "video_storage_gb": 0,
            "storage_limit_bytes": 536870912000,
            "is_active": False,
        },
        {
            "id": "4",
            "name": "Master Atelier",
            "subtitle": "Master",
            "tier": "premium",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 2500.00,
            "total_price": 30000.00,
            "currency": "INR",
            "image_storage_gb": 1000,
            "video_storage_gb": 0,
            "storage_limit_bytes": 1099511627776,
            "is_active": False,
        },
        # Primary Studio Tiers
        {
            "id": "plan-standard-3m",
            "name": "Standard Quarterly",
            "subtitle": "For 03 Months • Ideal For Getting Started",
            "tier": "standard",
            "billing_cycle": "quarterly",
            "duration_months": 3,
            "monthly_price": 800.00,
            "original_monthly_price": 1100.00,
            "total_price": 2400.00,
            "currency": "INR",
            "image_storage_gb": 200,
            "video_storage_gb": 10,
            "storage_limit_bytes": 225485783040,
            "tag": "",
            "tag_type": "default",
            "cta_text": "Choose Standard (3 Months)",
            "features": [
                "200 GB Image Storage",
                "10 GB Video Delivery",
                "For 03 Months Hosting",
                "Unlimited Client Galleries",
                "All 4 Layout Templates (Editorial, Masonry, Cinematic, Minimal)",
                "PIN Security & Custom Watermark Suite",
                "Priority Delivery Speeds"
            ],
            "is_active": True,
            "sort_order": 1,
        },
        {
            "id": "plan-standard-1y",
            "name": "Standard Annual",
            "subtitle": "For 01 Year • Best Value For Photographers",
            "tier": "standard",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 800.00,
            "original_monthly_price": 1100.00,
            "total_price": 9600.00,
            "currency": "INR",
            "image_storage_gb": 200,
            "video_storage_gb": 10,
            "storage_limit_bytes": 225485783040,
            "tag": "MOST POPULAR",
            "tag_type": "popular",
            "cta_text": "Choose Standard (1 Year)",
            "features": [
                "200 GB Image Storage",
                "10 GB Video Delivery",
                "For 01 Year Uninterrupted Hosting",
                "Unlimited Client Galleries",
                "All 4 Layout Templates (Editorial, Masonry, Cinematic, Minimal)",
                "PIN Security & Custom Watermark Suite",
                "Priority Delivery Speeds"
            ],
            "is_active": True,
            "sort_order": 2,
        },
        {
            "id": "plan-premium-elite",
            "name": "Studio Premium Elite",
            "subtitle": "For 01 Year • Maximum Storage & Dedicated Video Bandwidth",
            "tier": "premium",
            "billing_cycle": "annual",
            "duration_months": 12,
            "monthly_price": 1800.00,
            "original_monthly_price": 2400.00,
            "total_price": 21600.00,
            "currency": "INR",
            "image_storage_gb": 1000,
            "video_storage_gb": 50,
            "storage_limit_bytes": 1127428915200,
            "tag": "2X POWER",
            "tag_type": "popular",
            "cta_text": "Choose Studio Premium Elite",
            "features": [
                "1000 GB High-Speed Image Storage",
                "50 GB 4K Video Delivery",
                "Dedicated High-Bandwidth Cloud Delivery",
                "Custom Domain & Studio White-Labeling",
                "Advanced AI Face Search & Tagging",
                "Custom Studio Watermarking Suite",
                "VIP Support & Early Access to New Templates"
            ],
            "is_active": True,
            "sort_order": 3,
        },
    ]

    for item in seeds:
        Plan.objects.update_or_create(id=item["id"], defaults=item)


def update_subscriptions_after_alter(apps, schema_editor):
    Plan = apps.get_model('App', 'Plan')
    PhotographerSubscription = apps.get_model('App', 'PhotographerSubscription')
    PhotographerProfile = apps.get_model('App', 'PhotographerProfile')

    default_plan = Plan.objects.get(id="plan-standard-1y")

    # Map legacy integer-id subscriptions to the new standard 1-year plan
    for sub in PhotographerSubscription.objects.all():
        if str(sub.plan_id) in ["1", "2", "3", "4"]:
            sub.plan = default_plan
            sub.save(update_fields=['plan'])

    PhotographerProfile.objects.filter(studio_plan__isnull=True).update(
        studio_plan=default_plan
    )



class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_photographerprofile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(help_text="e.g. 'plan-standard-3m', 'plan-standard-1y'", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium Elite'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('quarterly', 'Quarterly (3 Months)'), ('annual', 'Annual (1 Year)'), ('monthly', 'Monthly')], default='quarterly', max_length=20)),
                ('duration_months', models.PositiveIntegerField(default=3)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('original_monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('image_storage_gb', models.PositiveIntegerField(default=200)),
                ('video_storage_gb', models.PositiveIntegerField(default=10)),
                ('storage_limit_bytes', models.BigIntegerField(default=225485783040)),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('tag_type', models.CharField(choices=[('default', 'Default'), ('popular', 'Popular'), ('current', 'Current')], default='default', max_length=20)),
                ('cta_text', models.CharField(default='Choose Plan', max_length=100)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'total_price'],
            },
        ),
        migrations.RunPython(seed_plans_before_alter, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='photographersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='legacy_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_subscriptions', to='App.subscriptionplans'),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='photographersubscription',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photographersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Payment'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('past_due', 'Past Due')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='studio_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='App.plan'),
        ),
        migrations.AlterField(
            model_name='photographersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='App.plan'),
        ),
        migrations.RunPython(update_subscriptions_after_alter, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gateway', models.CharField(default='razorpay', max_length=50)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='App.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='App.photographersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
