# Generated by Django 6.0.1 on 2026-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_plan_photographersubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographersubscription',
            name='extra_storage_gb',
            field=models.PositiveIntegerField(default=0, help_text='For Elite Plan storage add-on'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_portfolio_templates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_templates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_upgrade_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='face_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='gallery_expiry_days',
            field=models.PositiveIntegerField(default=90, help_text='0 for permanent/unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_full_inquiry_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_events',
            field=models.PositiveIntegerField(default=5, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_galleries',
            field=models.PositiveIntegerField(default=15, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_inquiries',
            field=models.PositiveIntegerField(default=10, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_portfolio_posts',
            field=models.PositiveIntegerField(default=10, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_upgrade_image_gb',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
