# Generated by Django 6.0.7 on 2026-09-22 04:50

import App.Subscriptions.sub_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_plan_photographersubscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allowed_portfolio_templates',
            field=models.JSONField(default=App.Subscriptions.sub_models.default_allowed_templates, help_text='List of allowed portfolio showcase layouts'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_templates',
            field=models.JSONField(default=App.Subscriptions.sub_models.default_allowed_templates, help_text='List of allowed gallery layouts for this tier'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_upgrade_storage',
            field=models.BooleanField(default=False, help_text='Whether this tier can purchase additional storage upgrades'),
        ),
        migrations.AddField(
            model_name='plan',
            name='face_search_enabled',
            field=models.BooleanField(default=True, help_text='Whether AI face search/discovery is enabled'),
        ),
        migrations.AddField(
            model_name='plan',
            name='gallery_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Gallery link/access validity in days (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_events',
            field=models.PositiveIntegerField(default=0, help_text='Max shared events allowed in event section (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_galleries',
            field=models.PositiveIntegerField(default=0, help_text='Max active client galleries (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_portfolio_posts',
            field=models.PositiveIntegerField(default=0, help_text='Max showcase portfolio posts (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_upgrade_image_gb',
            field=models.PositiveIntegerField(default=0, help_text='Maximum expandable image storage in GB (e.g. 1000 GB)'),
        ),
    ]
