# Generated by Django 6.0.7 on 2026-09-22 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_plan_allowed_portfolio_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_full_inquiry_access',
            field=models.BooleanField(default=True, help_text='Whether photographer can access all inquiries or only a sampled limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_inquiries',
            field=models.PositiveIntegerField(default=0, help_text='Max client inquiries accessible (0 for all/unlimited)'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, default='', max_length=20)),
                ('event_type', models.CharField(blank=True, default='Wedding', max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('budget', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(blank=True, help_text='Direct inquiry to specific photographer, or null for general lead pool', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='App.photographerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
