# Generated by Django 6.0.1 on 2026-09-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_photographersubscription_extra_storage_gb_and_more'),
        ('App', '0013_plan_has_full_inquiry_access_plan_max_inquiries_and_more'),
    ]

    operations = [
    ]
