# Generated by Django 6.0.1 on 2026-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_plan_has_full_inquiry_access_plan_max_inquiries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographersubscription',
            name='extra_storage_gb',
            field=models.PositiveIntegerField(default=0, help_text='For Elite Plan storage add-on'),
        ),
    ]
