# Generated by Django 6.0.1 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_plan_allowed_portfolio_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='galleries/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='media',
            name='section_title',
            field=models.CharField(db_index=True, default='Highlights', max_length=100),
        ),
    ]
