# Generated by Django 6.0.1 on 2026-09-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_gallery_sections_media_file_media_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=750),
        ),
        migrations.AddField(
            model_name='gallery',
            name='download_pin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='masonry_banner_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of up to 4 image URLs for the Masonry mosaic header'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='template_banners',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary mapping templateId to hero banner URL, e.g. {'editorial': 'https://...', 'cinematic': 'https://...'}"),
        ),
        migrations.AddField(
            model_name='media',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='template_id',
            field=models.CharField(choices=[('editorial', 'Editorial High-Fashion'), ('masonry', 'Dynamic Masonry Mosaic'), ('slideshow', 'Full-bleed Cinematic Slideshow'), ('filmstrip', 'Horizontal Filmstrip Flow'), ('minimal', 'Fine Art Minimal White'), ('columns', 'Multi-Column Grid'), ('grid', 'Classic Balanced Grid'), ('cinematic', 'Widescreen Cinematic')], default='editorial', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='GalleryAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'Gallery View'), ('download', 'Photo or Zip Download'), ('favorite', 'Photo Favorited'), ('share', 'Gallery Shared')], db_index=True, max_length=20)),
                ('device', models.CharField(default='desktop', max_length=20)),
                ('traffic_source', models.CharField(default='direct_link', max_length=30)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='App.gallery')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='App.media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='App.gallery')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='App.gallerysection'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'section_title'], name='App_media_gallery_6c433e_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryanalyticsevent',
            index=models.Index(fields=['gallery', 'event_type', 'created_at'], name='App_gallery_gallery_f62fc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gallerysection',
            unique_together={('gallery', 'title')},
        ),
    ]
