# Generated by Django 6.0.1 on 2026-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_gallery_client_phone_gallery_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['display_order', '-created_at', 'id']},
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'display_order', '-created_at', 'id'], name='App_media_gallery_6979f3_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'section_title', 'display_order', '-created_at', 'id'], name='App_media_gallery_ba8260_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'is_favorite', 'display_order', '-created_at', 'id'], name='App_media_gallery_bcadfb_idx'),
        ),
    ]
