# Generated by Django 6.0.1 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='UTC timestamp when client viewing access expires. NULL means permanent access (never expires).', null=True),
        ),
    ]
