# Generated by Django 6.0.1 on 2026-09-28 04:53

import uuid
from django.db import migrations, models


class SafeAlterGallerySectionId(migrations.AlterField):
    """
    Safely alter GallerySection.id from BigAutoField to UUIDField.
    PostgreSQL cannot cast type bigint to uuid directly, and foreign keys in App_media
    prevent in-place altering of the primary key column.
    This operation handles PostgreSQL gracefully while preserving standard Django
    behavior on SQLite.
    """
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            with schema_editor.connection.cursor() as cursor:
                # 1. Back up any existing gallerysection rows in memory
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'App_gallerysection'
                    );
                """)
                table_exists = cursor.fetchone()[0]
                rows = []
                if table_exists:
                    try:
                        cursor.execute('SELECT gallery_id, title, "order", created_at FROM "App_gallerysection";')
                        rows = cursor.fetchall()
                    except Exception:
                        rows = []

                # 2. Drop existing App_gallerysection table CASCADE
                # This drops the bigint PK and any FK constraints on App_media
                cursor.execute('DROP TABLE IF EXISTS "App_gallerysection" CASCADE;')

                # 3. Alter App_media.section_id column to UUID
                cursor.execute('ALTER TABLE "App_media" DROP COLUMN IF EXISTS "section_id";')
                cursor.execute('ALTER TABLE "App_media" ADD COLUMN "section_id" uuid NULL;')

                # 4. Recreate App_gallerysection with UUID primary key
                cursor.execute('''
                    CREATE TABLE "App_gallerysection" (
                        "id" uuid NOT NULL PRIMARY KEY,
                        "title" varchar(120) NOT NULL,
                        "order" integer CHECK ("order" >= 0) NOT NULL DEFAULT 0,
                        "created_at" timestamp with time zone NOT NULL,
                        "gallery_id" uuid NOT NULL REFERENCES "App_gallery" ("id") DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT "App_gallerysection_gallery_id_title_uniq" UNIQUE ("gallery_id", "title")
                    );
                ''')
                cursor.execute('CREATE INDEX IF NOT EXISTS "App_gallerysection_gallery_id_idx" ON "App_gallerysection" ("gallery_id");')

                # 5. Restore rows if any existed
                for row in rows:
                    cursor.execute(
                        'INSERT INTO "App_gallerysection" ("id", "gallery_id", "title", "order", "created_at") VALUES (%s, %s, %s, %s, %s)',
                        [str(uuid.uuid4()), row[0], row[1], row[2], row[3]]
                    )

                # 6. Re-add FK constraint from App_media to App_gallerysection
                cursor.execute('''
                    ALTER TABLE "App_media" ADD CONSTRAINT "App_media_section_id_fk_App_gallerysection_id"
                    FOREIGN KEY ("section_id") REFERENCES "App_gallerysection" ("id") DEFERRABLE INITIALLY DEFERRED;
                ''')
                cursor.execute('CREATE INDEX IF NOT EXISTS "App_media_section_id_idx" ON "App_media" ("section_id");')
        else:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_gallery_expires_at'),
    ]

    operations = [
        SafeAlterGallerySectionId(
            model_name='gallerysection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
