# Generated by Django on 2026-09-28
from django.db import migrations


def remove_test_plan(apps, schema_editor):
    Plan = apps.get_model('App', 'Plan')
    PhotographerSubscription = apps.get_model('App', 'PhotographerSubscription')
    PhotographerProfile = apps.get_model('App', 'PhotographerProfile')

    test_plan = Plan.objects.filter(id='plan-test-20gb').first()
    if test_plan:
        fallback_plan = (
            Plan.objects.filter(id='plan-standard-1y').first()
            or Plan.objects.exclude(id='plan-test-20gb').first()
        )
        if fallback_plan:
            PhotographerSubscription.objects.filter(plan=test_plan).update(plan=fallback_plan)
            PhotographerProfile.objects.filter(studio_plan=test_plan).update(studio_plan=fallback_plan)
        else:
            PhotographerSubscription.objects.filter(plan=test_plan).update(plan=None)
            PhotographerProfile.objects.filter(studio_plan=test_plan).update(studio_plan=None)
        test_plan.delete()


def backward_pass(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_gallerysection_id'),
    ]

    operations = [
        migrations.RunPython(remove_test_plan, backward_pass),
    ]
