# Generated by Django 6.0.1 on 2026-09-28 06:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_test_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='events/photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbs/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('section_title', models.CharField(default='CEREMONY', max_length=100)),
                ('width', models.PositiveIntegerField(default=1920)),
                ('height', models.PositiveIntegerField(default=1080)),
                ('aspect_ratio', models.FloatField(default=1.77)),
                ('size_mb', models.FloatField(default=3.5)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_id', models.CharField(blank=True, max_length=100)),
                ('embedding', models.JSONField(help_text='512-dim face recognition vector')),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='App.eventmedia')),
            ],
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, default='Private Client', max_length=255)),
                ('client_contact', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding Celebration'), ('reception', 'Reception / Sangeet'), ('gala', 'VIP Gala / Soirée'), ('fashion', 'Fashion Show'), ('birthday', 'Birthday / Anniversary'), ('corporate', 'Corporate Summit'), ('concert', 'Concert / Performance'), ('other', 'Special Event')], default='wedding', max_length=50)),
                ('status', models.CharField(choices=[('live', 'Live Streaming'), ('upcoming', 'Upcoming Scheduled'), ('completed', 'Completed'), ('trash', 'In Trash')], db_index=True, default='live', max_length=30)),
                ('banner_url', models.URLField(blank=True, default='', max_length=1000)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_time', models.CharField(blank=True, default='18:00', max_length=20)),
                ('venue', models.CharField(blank=True, default='Private Venue', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('qr_valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_duration_hours', models.IntegerField(default=24)),
                ('qr_pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('allow_guest_uploads', models.BooleanField(default=False)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('guest_views', models.PositiveIntegerField(default=0)),
                ('qr_scans', models.PositiveIntegerField(default=0)),
                ('ai_searches', models.PositiveIntegerField(default=0)),
                ('matches_found', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='App.liveevent'),
        ),
    ]
