# Generated by Django 6.0.1 on 2026-09-28 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_eventmedia_eventfaceembedding_liveevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='file',
            field=models.FileField(upload_to='events/media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='events/thumbs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
