# Generated by Django 6.0.1 on 2026-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_eventmedia_file_alter_eventmedia_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20),
        ),
    ]
