# Generated by Django 6.0.1 on 2026-09-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_eventmedia_file_size_eventmedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='section_title',
            field=models.CharField(default='HIGHLIGHTS', max_length=100),
        ),
    ]
