# Generated by Django 6.0.1 on 2026-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_eventmedia_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='face_search_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
