# Generated by Django 6.0.1 on 2026-09-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_gallery_face_search_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveevent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding Celebration'), ('reception', 'Reception / Sangeet'), ('sangeet', 'Sangeet / Mehendi'), ('gala', 'VIP Gala / Soirée'), ('fashion', 'Fashion Show'), ('birthday', 'Birthday / Anniversary'), ('anniversary', 'Anniversary Celebration'), ('corporate', 'Corporate Summit'), ('concert', 'Concert / Performance'), ('other', 'Special Event')], default='wedding', max_length=50),
        ),
    ]
