# Generated by Django 6.0.1 on 2026-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_liveevent_city_alter_liveevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='status',
            field=models.CharField(choices=[('live', 'Live Streaming'), ('upcoming', 'Upcoming Scheduled'), ('completed', 'Completed'), ('moved_to_gallery', 'Moved to Gallery'), ('trash', 'In Trash'), ('archived', 'Archived')], db_index=True, default='live', max_length=30),
        ),
    ]
