# Generated by Django 6.0.7 on 2026-10-01 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_liveevent_deleted_at_alter_liveevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='storage_limit_bytes',
            field=models.BigIntegerField(blank=True, default=16106127360, null=True),
        ),
        migrations.AddField(
            model_name='photographersubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photographersubscription',
            name='photographer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='App.photographerprofile'),
        ),
    ]
