# Generated by Django 6.0.7 on 2026-10-01 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_photographersubscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_inquiries', models.BooleanField(default=True, help_text='Send email when a client submits booking inquiry')),
                ('inapp_inquiries', models.BooleanField(default=True, help_text='Show in-app bell alert for inquiries')),
                ('email_gallery_visited', models.BooleanField(default=True, help_text='Email alert when client first unlocks gallery')),
                ('email_gallery_download', models.BooleanField(default=True, help_text='Email alert when high-res ZIP package download is started')),
                ('inapp_gallery_activity', models.BooleanField(default=True, help_text='In-app notification for gallery publish & client favorites')),
                ('email_event_activity', models.BooleanField(default=True, help_text='Email digest of live event guest interactions')),
                ('inapp_event_activity', models.BooleanField(default=True, help_text='In-app live feed for guest uploads and QR scans')),
                ('email_billing_alerts', models.BooleanField(default=True, help_text='Email payment receipts, renewal notices & cancellation receipts')),
                ('inapp_billing_alerts', models.BooleanField(default=True, help_text='In-app warnings for plan renewal or pending expiration')),
                ('email_storage_warnings', models.BooleanField(default=True, help_text='Send critical warning email at 85% and 95% disk usage')),
                ('inapp_storage_warnings', models.BooleanField(default=True, help_text='In-app warning banner when nearing storage limit')),
                ('email_weekly_digest', models.BooleanField(default=True, help_text='Weekly studio performance summary')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studio Notification Settings',
                'verbose_name_plural': 'Studio Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='StudioNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('inquiry', 'Client Inquiry'), ('gallery', 'Gallery Delivery'), ('event', 'Live Event'), ('plan', 'Studio Plan & Billing'), ('storage', 'Storage & Quota'), ('system', 'System & Security')], default='system', max_length=32)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent Alert')], default='normal', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=512, null=True)),
                ('action_label', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='App_studion_user_id_23f7db_idx'), models.Index(fields=['user', 'created_at'], name='App_studion_user_id_b4ef6a_idx'), models.Index(fields=['user', 'type'], name='App_studion_user_id_441b7f_idx')],
            },
        ),
    ]
