# Generated by Django 6.0.7 on 2026-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_studionotificationsettings_studionotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tag_type',
            field=models.CharField(choices=[('default', 'Default'), ('popular', 'Popular'), ('current', 'Current'), ('elite', 'Elite')], default='default', max_length=20),
        ),
    ]
