# Generated by Django 6.0.7 on 2026-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_plan_is_popular_alter_plan_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='watermark_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether watermarking is enabled for photos in this gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_opacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='watermark_enabled',
            field=models.BooleanField(default=False, help_text='Whether photographers on this plan can apply watermarks to gallery photos'),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom_right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('bottom_left', 'Bottom Left'), ('top-right', 'Top Right'), ('top_right', 'Top Right'), ('center', 'Center'), ('tiled', 'Tiled Pattern'), ('repeated', 'Repeated Pattern')], default='bottom-right', max_length=50),
        ),
    ]
