# Generated by Django 6.0.7 on 2026-10-05 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_gallery_watermark_enabled_gallery_watermark_opacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CullingClusterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_number', models.PositiveIntegerField(default=1)),
                ('average_similarity', models.FloatField(default=0.0)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('duplicates_count', models.PositiveIntegerField(default=0)),
                ('wasted_bytes', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['cluster_number'],
            },
        ),
        migrations.CreateModel(
            name='CullingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='culling_uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('dhash_string', models.CharField(blank=True, default='', max_length=64)),
                ('laplacian_variance', models.FloatField(default=0.0)),
                ('sharpness_score', models.PositiveIntegerField(default=50)),
                ('similarity_with_winner', models.FloatField(default=100.0)),
                ('is_best_pick', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('keep', 'Keep'), ('discard', 'Discard')], default='keep', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='App.cullingclustergroup')),
            ],
            options={
                'ordering': ['-sharpness_score', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='cullingclustergroup',
            name='best_pick_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_clusters', to='App.cullingitem'),
        ),
        migrations.CreateModel(
            name='CullingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Shoot Culling', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_tier', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('keeper_count', models.PositiveIntegerField(default=0)),
                ('total_saved_bytes', models.BigIntegerField(default=0)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('progress_status_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CullingPaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('tier_name', models.CharField(default='Single Shoot Batch', max_length=100)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paisa', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='App.cullingsession')),
            ],
        ),
        migrations.AddField(
            model_name='cullingitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.cullingsession'),
        ),
        migrations.AddField(
            model_name='cullingclustergroup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='App.cullingsession'),
        ),
    ]
