# Generated by Django 6.0.7 on 2026-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_cullingclustergroup_cullingitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerprofile',
            name='enable_watermark',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_opacity',
            field=models.FloatField(default=0.45, help_text='Opacity between 0.1 and 1.0 (default 0.45)'),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_text',
            field=models.CharField(blank=True, default='', help_text="Custom watermark signature. If blank, defaults to photographer's name.", max_length=255),
        ),
    ]
