# Generated by Django 6.0.7 on 2026-10-05 06:34

import App.Culling.culling_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_migrate_watermark_placeholders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cullingitem',
            old_name='file_size_bytes',
            new_name='size_bytes',
        ),
        migrations.RemoveField(
            model_name='cullingitem',
            name='dhash_string',
        ),
        migrations.RemoveField(
            model_name='cullingitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cullingitem',
            name='laplacian_variance',
        ),
        migrations.AddField(
            model_name='cullingitem',
            name='assigned_category',
            field=models.CharField(default='HIGHLIGHTS', max_length=100),
        ),
        migrations.AddField(
            model_name='cullingitem',
            name='dhash_hex',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cullingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=App.Culling.culling_models.culling_upload_path),
        ),
        migrations.AddField(
            model_name='cullingitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=App.Culling.culling_models.culling_thumb_path),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='max_photos_allowed',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='cullingitem',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='App.cullingclustergroup'),
        ),
        migrations.AlterField(
            model_name='cullingitem',
            name='sharpness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cullingitem',
            name='similarity_with_winner',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cullingitem',
            name='status',
            field=models.CharField(choices=[('keep', 'Keep (Approved Winner)'), ('discard', 'Discard (Inferior Duplicate)')], default='keep', max_length=10),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='paid_tier',
            field=models.CharField(choices=[('cull_single_300', 'Single Shoot Batch (Up to 300) - ₹149'), ('cull_wedding_1200', 'Full Event / Wedding (Up to 1,200) - ₹249'), ('cull_pro_unlimited', 'Studio Pro Unlimited - ₹499')], default='cull_single_300', max_length=50),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Awaiting Payment)'), ('paid', 'Paid & Processing'), ('analyzing', 'AI Analyzing'), ('ready', 'Cull Ready For Review'), ('completed', 'Completed & Moved to Gallery'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='title',
            field=models.CharField(default='AI Shoot Culling', max_length=255),
        ),
    ]
