# Generated by Django 6.0.7 on 2026-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_rename_file_size_bytes_cullingitem_size_bytes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', 'display_order', '-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'order'], name='App_media_gallery_09645e_idx'),
        ),
    ]
