# Generated by Django 6.0.7 on 2026-10-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_alter_media_options_media_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cullingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_culling_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
