# Generated by Django 6.0.7 on 2026-10-05 08:44

import App.Storage.storage_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_cullingsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(db_index=True, help_text="Unique client token stored in visitor's localStorage", max_length=128, unique=True)),
                ('name', models.CharField(default='Guest Creator', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='App.gallery')),
            ],
            options={
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryStoryVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_name', models.CharField(default='Guest Creator', max_length=120)),
                ('title', models.CharField(default='Our Story', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('aspect_ratio', models.CharField(choices=[('9:16', '9:16 Vertical (Reel / Story / Status)'), ('1:1', '1:1 Square (Instagram Feed)'), ('16:9', '16:9 Widescreen (Cinematic / TV)')], default='9:16', max_length=10)),
                ('transition_style', models.CharField(choices=[('ken-burns', 'Ken Burns (Cinematic Drift)'), ('crossfade', 'Dreamy Dissolve (Crossfade)'), ('burst', 'Dynamic Burst'), ('fade-black', 'Classic Noir (Fade to Black)')], default='ken-burns', max_length=20)),
                ('duration_seconds', models.FloatField(default=15.0)),
                ('music_title', models.CharField(blank=True, default='Soundtrack', max_length=255)),
                ('music_artist', models.CharField(blank=True, default='', max_length=255)),
                ('music_url', models.CharField(blank=True, default='', max_length=1024)),
                ('photo_ids', models.JSONField(default=list)),
                ('video_file', models.FileField(max_length=512, upload_to=App.Storage.storage_models.story_video_upload_path)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('is_public_story', models.BooleanField(default=True, help_text="If true, visible in the gallery's guest stories showcase")),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_videos', to='App.gallery')),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_videos', to='App.galleryguestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_story_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryguestsession',
            index=models.Index(fields=['gallery', 'guest_token'], name='App_gallery_gallery_e8c04c_idx'),
        ),
        migrations.AddIndex(
            model_name='gallerystoryvideo',
            index=models.Index(fields=['gallery', 'created_at'], name='App_gallery_gallery_a96aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='gallerystoryvideo',
            index=models.Index(fields=['guest_session'], name='App_gallery_guest_s_e18bd6_idx'),
        ),
    ]
