# Generated by Django 6.0.7 on 2026-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_galleryguestsession_gallerystoryvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_culling_enabled',
            field=models.BooleanField(default=False, help_text='Enables AI Smart Culling & Duplicate Detection for subscribers on this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='ai_culling_enabled',
            field=models.BooleanField(default=False, help_text='Whether AI Smart Culling is enabled'),
        ),
    ]
