# Generated by Django 6.0.7 on 2026-10-08 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_plan_ai_culling_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code for watermark typography', max_length=20),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_font_size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large')], default='md', help_text='Typography size preset: sm, md, lg, xl', max_length=10),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_font_style',
            field=models.CharField(choices=[('serif', 'Editorial Serif'), ('sans', 'Modern Sans'), ('script', 'Signature Script'), ('mono', 'Minimal Mono')], default='serif', help_text='Typography family: serif, sans, script, mono', max_length=20),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='watermark_type',
            field=models.CharField(choices=[('text', 'Text Signature'), ('image', 'Image Logo')], default='text', help_text="Active branding format: 'text' or 'image'", max_length=10),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='enable_watermark',
            field=models.BooleanField(default=True, help_text='Enable or disable watermark branding on client galleries'),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_image',
            field=models.ImageField(blank=True, help_text='Studio watermark logo (transparent PNG/SVG recommended)', null=True, upload_to='watermarks/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_opacity',
            field=models.FloatField(default=0.45, help_text='Opacity between 0.05 and 1.0 (default 0.45)', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='watermark_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom_right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('bottom_left', 'Bottom Left'), ('top-right', 'Top Right'), ('top_right', 'Top Right'), ('top-left', 'Top Left'), ('top_left', 'Top Left'), ('center', 'Center'), ('tiled', 'Tiled Pattern'), ('repeated', 'Repeated Pattern')], default='bottom-right', help_text='Watermark screen placement', max_length=50),
        ),
    ]
