# Generated by Django 6.0.7 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_photographerprofile_watermark_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='watermark_font_color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_font_size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_font_style',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='watermark_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Signature'), ('image', 'Image Logo')], default=None, help_text="Active branding format: 'text' or 'image'", max_length=10, null=True),
        ),
    ]
