# Generated by Django 6.0.7 on 2026-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_gallery_watermark_font_color_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['gallery', 'is_favorite'], name='idx_media_gallery_favorite'),
        ),
    ]
