# Generated by Django 6.0.7 on 2026-10-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_media_idx_media_gallery_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
