# Generated by Django 6.0.7 on 2026-10-05 08:20

import culling.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CullingPricingTier',
            fields=[
                ('id', models.CharField(help_text='Unique tier slug/id, e.g. cull_single_300, cull_wedding_1200, cull_pro_unlimited', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_inr', models.PositiveIntegerField(help_text='Price in INR, e.g. 149')),
                ('photos_limit', models.PositiveIntegerField(help_text='Maximum photos permitted in one session. Use 999999 for unlimited.')),
                ('badge', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet strings displayed in UI')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'photos_limit'],
            },
        ),
        migrations.CreateModel(
            name='CullingSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active Batch In Progress'), ('completed', 'Completed (Moved to Gallery)'), ('exported', 'Exported via ZIP'), ('discarded', 'Discarded & Storage Cleared'), ('expired', 'Expired / Auto-Purged')], db_index=True, default='pending_payment', max_length=24)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount_inr', models.PositiveIntegerField(default=0)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('total_clusters', models.PositiveIntegerField(default=0)),
                ('total_duplicates', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='culling.cullingpricingtier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CullingPhoto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=512, upload_to=culling.models.culling_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('size_mb', models.FloatField(default=0.0)),
                ('sharpness_score', models.FloatField(default=0.0)),
                ('raw_sharpness_variance', models.FloatField(default=0.0)),
                ('cluster_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('is_best_pick', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('keep', 'Keep'), ('discard', 'Discard')], db_index=True, default='keep', max_length=12)),
                ('similarity_with_best', models.FloatField(default=0.0)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='culling.cullingsession')),
            ],
            options={
                'ordering': ['cluster_id', '-sharpness_score'],
            },
        ),
        migrations.CreateModel(
            name='CullingCluster',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('best_pick_id', models.CharField(blank=True, default='', max_length=128)),
                ('photo_ids', models.JSONField(default=list)),
                ('average_similarity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='culling.cullingsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cullingsession',
            index=models.Index(fields=['user', 'status'], name='culling_cul_user_id_14aa8d_idx'),
        ),
    ]
