# Generated by Django 6.0.7 on 2026-10-05 11:24

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cullingphoto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cullingpricingtier',
            options={'ordering': ['display_order', 'price']},
        ),
        migrations.RenameIndex(
            model_name='cullingsession',
            new_name='culling_ses_user_id_da5b56_idx',
            old_name='culling_cul_user_id_14aa8d_idx',
        ),
        migrations.AddField(
            model_name='cullingcluster',
            name='best_pick_item_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cullingcluster',
            name='duplicates_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingcluster',
            name='title',
            field=models.CharField(default='Burst Set', max_length=100),
        ),
        migrations.AddField(
            model_name='cullingcluster',
            name='total_photos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cullingcluster',
            name='wasted_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingphoto',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingphoto',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cullingphoto',
            name='perceptual_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cullingphoto',
            name='similarity_with_winner',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cullingpricingtier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cullingpricingtier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('149.00'), help_text='Price in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='cullingpricingtier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='photo_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='title',
            field=models.CharField(default='AI Smart Cull Session', max_length=255),
        ),
        migrations.AlterField(
            model_name='cullingcluster',
            name='average_similarity',
            field=models.FloatField(default=90.0),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='cluster_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='raw_sharpness_variance',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='sharpness_score',
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='similarity_with_best',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cullingphoto',
            name='status',
            field=models.CharField(choices=[('keep', 'Keep'), ('discard', 'Discard')], db_index=True, default='keep', max_length=20),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='e.g. Up to 300 Photos', max_length=100),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='id',
            field=models.CharField(help_text='Unique tier slug/id, e.g. tier_starter, tier_pro, tier_wedding', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='name',
            field=models.CharField(help_text='e.g. Starter Shoot, Studio Event', max_length=120),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='photos_limit',
            field=models.PositiveIntegerField(default=300, help_text='Maximum photos permitted in one batch. Use 999999 for unlimited.'),
        ),
        migrations.AlterField(
            model_name='cullingpricingtier',
            name='price_inr',
            field=models.PositiveIntegerField(default=149, help_text='Price in INR integer fallback'),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft / Staging'), ('paid', 'Paid & Unlocked'), ('analyzed', 'Analyzed & Curated'), ('moved_to_gallery', 'Moved to Gallery'), ('discarded', 'Discarded / Purged'), ('pending_payment', 'Pending Payment'), ('active', 'Active Batch In Progress'), ('completed', 'Completed (Moved to Gallery)'), ('exported', 'Exported via ZIP'), ('expired', 'Expired / Auto-Purged')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterModelTable(
            name='cullingcluster',
            table='culling_cluster',
        ),
        migrations.AlterModelTable(
            name='cullingphoto',
            table='culling_photo',
        ),
        migrations.AlterModelTable(
            name='cullingpricingtier',
            table='culling_pricing_tier',
        ),
        migrations.AlterModelTable(
            name='cullingsession',
            table='culling_session',
        ),
    ]
