# Generated by Django 6.0.7 on 2026-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0002_alter_cullingphoto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CullingPhoto',
            new_name='CullingStagingPhoto',
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='keeper_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cullingsession',
            name='wasted_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cullingsession',
            name='status',
            field=models.CharField(choices=[('staging', 'Staging / Uploading'), ('draft', 'Draft / Staging'), ('analyzed', 'Analyzed & Curated'), ('moved_to_gallery', 'Moved to Gallery'), ('discarded', 'Discarded / Purged'), ('paid', 'Paid & Unlocked'), ('active', 'Active Batch In Progress'), ('completed', 'Completed (Moved to Gallery)')], db_index=True, default='staging', max_length=30),
        ),
    ]
