# Generated by Django 6.0.7 on 2026-10-07 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0003_rename_cullingphoto_cullingstagingphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cullingcluster',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
    ]
