# Generated by Django 6.0.7 on 2026-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culling', '0004_alter_cullingcluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cullingstagingphoto',
            name='face_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI-detected facial analysis: landmarks, eyes, lips, expression data'),
        ),
    ]
