# Generated by Django 6.0.7 on 2026-10-06 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(choices=[('darkroom-atelier', 'Obsidian Noir (Dark)'), ('editorial-vogue', 'Lumina Pure (Light)')], default='darkroom-atelier', max_length=64)),
                ('studio_name', models.CharField(default='My Photography Studio', max_length=255)),
                ('artist_name', models.CharField(default='Lead Artist', max_length=255)),
                ('tagline', models.TextField(default='Visual Storytelling • Luxury Documentaries & Fine Art')),
                ('bio', models.TextField(blank=True, default='Documenting raw emotion, modern romanticism, and timeless moments.')),
                ('about_story', models.TextField(blank=True, default='Our studio blends documentary photojournalism with refined fine-art aesthetics.')),
                ('location', models.CharField(default='Mumbai & Worldwide', max_length=255)),
                ('avatar_url', models.URLField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', max_length=1024)),
                ('banner_url', models.URLField(default='https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1920&auto=format&fit=crop&q=85', max_length=1024)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('instagram_handle', models.CharField(blank=True, default='', max_length=128)),
                ('youtube_handle', models.CharField(blank=True, default='', max_length=128)),
                ('website_url', models.URLField(blank=True, default='', max_length=512)),
                ('is_booking_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Configuration',
                'verbose_name_plural': 'Portfolio Configurations',
                'db_table': 'portfolio_config',
            },
        ),
        migrations.CreateModel(
            name='PortfolioInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('pre-wedding', 'Pre-Wedding'), ('editorial', 'Editorial / Fashion'), ('commercial', 'Commercial'), ('portrait', 'Portrait Session'), ('workshop', 'Workshop / Mentorship'), ('maternity', 'Maternity'), ('other', 'Other')], default='wedding', max_length=64)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('budget', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'In Discussion'), ('booked', 'Confirmed Booked'), ('archived', 'Archived')], default='new', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Inquiry',
                'verbose_name_plural': 'Portfolio Inquiries',
                'db_table': 'portfolio_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('weddings', 'Weddings'), ('editorial', 'Editorial'), ('commercial', 'Commercial'), ('pre-wedding', 'Pre-Wedding'), ('cinematic', 'Cinematic'), ('portrait', 'Portrait')], default='weddings', max_length=64)),
                ('cover_url', models.URLField(max_length=1024)),
                ('year', models.CharField(default='2026', max_length=16)),
                ('location', models.CharField(default='Location', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='portfolio.portfolioconfig')),
            ],
            options={
                'verbose_name': 'Portfolio Work',
                'verbose_name_plural': 'Portfolio Works',
                'db_table': 'portfolio_work',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=1024)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.portfoliowork')),
            ],
            options={
                'verbose_name': 'Portfolio Work Photo',
                'verbose_name_plural': 'Portfolio Work Photos',
                'db_table': 'portfolio_work_photo',
                'ordering': ['order', 'id'],
            },
        ),
    ]
