# Generated by Django 6.0.7 on 2026-10-06 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinquiry',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], default='mobile', max_length=16)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('page_section', models.CharField(default='hero', max_length=64)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio View Event',
                'verbose_name_plural': 'Portfolio View Events',
                'db_table': 'portfolio_view',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['photographer', 'created_at'], name='portfolio_v_photogr_762f35_idx'), models.Index(fields=['photographer', 'project_id'], name='portfolio_v_photogr_0bbca3_idx')],
            },
        ),
    ]
