# Generated by Django 6.0.7 on 2026-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioinquiry_project_id_portfolioview'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioview',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='visitor_ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioview',
            name='referrer',
            field=models.CharField(blank=True, default='direct', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioview',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
