# Generated by Django 6.0.7 on 2026-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioview_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioconfig',
            name='template_id',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('masonry', 'Masonry'), ('cinematic', 'Cinematic'), ('minimal', 'Minimal'), ('darkroom-atelier', 'Darkroom Atelier (Masonry)'), ('editorial-vogue', 'Editorial Vogue'), ('cinematic-luxury', 'Cinematic Luxury'), ('minimal-zen', 'Minimal Zen')], default='darkroom-atelier', max_length=64),
        ),
    ]
