# Generated by Django 6.0.7 on 2026-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioconfig_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('reason', models.CharField(default='system_reserved', max_length=255)),
                ('reserved_for_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reserved Subdomain',
                'verbose_name_plural': 'Reserved Subdomains',
                'db_table': 'portfolio_reserved_subdomain',
            },
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text="Independent custom domain, e.g. 'elena-photography.com'", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this showcase portfolio is published and accessible to public visitors'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, help_text="Custom unique subdomain label under base domain, e.g. 'mridhul' for mridhul.exshare.ai", max_length=63, null=True, unique=True),
        ),
    ]
