# Generated by Django 6.0.7 on 2026-10-10 09:57

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_reservedsubdomain_portfolioconfig_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='accent_color',
            field=models.CharField(default='#d4af37', max_length=32),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='philosophy_author',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='philosophy_quote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='pricing_starting_at',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this project work is published in the portfolio showcase'),
        ),
        migrations.AlterField(
            model_name='portfolioconfig',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, help_text="Custom unique subdomain label under base domain, e.g. 'mridhul' for mridhul.exshare.ai", max_length=63, null=True, unique=True, validators=[portfolio.models.validate_subdomain]),
        ),
    ]
