# Generated by Django 6.0.7 on 2026-10-10 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolioconfig_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfig',
            name='whatsapp_button_label',
            field=models.CharField(blank=True, default='Chat on WhatsApp', help_text='Text shown on the floating pill or hover tooltip.', max_length=64),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Controls whether the floating WhatsApp button is rendered on the public portfolio.'),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='International phone number for WhatsApp direct contact (e.g. +919876543210).', max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in international format: e.g. '+919876543210' or '+15551234567'.", regex='^\\+?[1-9]\\d{6,14}$')]),
        ),
        migrations.AddField(
            model_name='portfolioconfig',
            name='whatsapp_prefill_message',
            field=models.TextField(blank=True, default="Hi, I'm interested in booking a photography session with your studio!", help_text='Default message pre-filled in the WhatsApp chat when clients click the button.'),
        ),
    ]
